### ISSUE TITLE
Class 'App\Eloquent' not found

### ISSUE THREAD

**Issue by OctaneInteractive** [elasticquent/Elasticquent#146]
Hi, I'm using:

- AWS Ubuntu 16.04.2 LTS on an EC2 Instance.
- AWS Elasticsearch Service.
- PHP 7.1
- Laravel 5.4

Having followed the instructions, I have the following:

```
<?php

namespace App;

use Elasticquent\ElasticquentTrait;

class VenuesSearch extends Eloquent
{
	use ElasticquentTrait;
}
```

... which is the file: `VenuesSearch.php`.

However, this gives me the error:

> (1/1) FatalErrorException
> Class 'App\Eloquent' not found
> in VenuesSearch.php (line 8)

I'm assuming I'd access this model from a controller to run searches? I ask because the instructions aren't clear to me, and there a too few examples of code to use.

I've gone through the instructions and I don't see anything obvious missing or wrong.

However, I am new to Composer, and when I ran `git status` I don't see files for Elasticquent.

**Comment by brunogaspar** [comment]
Since you're under a namespace, you'll need to also import Eloquent.

Just add `use Eloquent;` after your namespace declaration and it should work.

However, the proper way is to import the FQCN instead of the Laravel alias.

To do that, just add `use Illuminate\Database\Eloquent\Model;` (pretty much like the above) and then modify the `extends Eloquent` part to be `extends Model`, like so:

```php
<?php

namespace App;

use Elasticquent\ElasticquentTrait;
use Illuminate\Database\Eloquent\Model;

class VenuesSearch extends Model
{
	use ElasticquentTrait;
}
```

Hope it helps.

**Comment by timgws** [comment]
Thanks @brunogaspar !
