### ISSUE TITLE
Content-Type header [] is not supported

### ISSUE THREAD

**Issue by etertime** [elasticquent/Elasticquent#154]
```
$enterprise = Enterprise::where('id','<',200)->get();
 $enterprise->addToIndex();

```
response error
> Content-Type header [] is not supported

How to specify the head of a request ?
like this
` curl -H "Content-Type: application/json;charset=UTF-8" -XGET 'http://127.0.0.1:9200/_count?pretty' -d '{"query":{"match_all":{}}}'  `

Content-type header can be specified here

not like 
` curl -XGET 'http://127.0.0.1:9200/_count?pretty' -d '{"query":{"match_all":{}}}'  `
Otherwise it will be wrong:
```
{
  "error" : "Content-Type header [application/x-www-form-urlencoded] is not supported",
  "status" : 406
}
```
How should I solve it, Who can help me?
Oh,the problem is in the elasticsearch 6.0.0

**Comment by valterlorran** [comment]
Hey, did you solve this?

**Comment by fikrystark** [comment]
Please update this, i have same issue here..

**Comment by valterlorran** [comment]
@fikrystark  i think this project do not support the new versions of elasticsearch. I just used the default php library.

**Comment by chadidi** [comment]
I have the same problem did anyone fixed it yet I am running elasticsearch-6.1.1

**Comment by rodrigue67** [comment]
same problem for me, anybody know how we can solve this BUG ?

**Comment by CyberDracula** [comment]
Until a proper fix I made a fork [https://github.com/CyberDracula/Elasticquent](url) where I changed the required version for elasticsearch/elasticsearch to the latest. So far everything i use seems to work with 61.1.

**Comment by filesearchme** [comment]
same issue here

**Comment by coffeeburrito** [comment]
Problem summary:
- Elasticquent only supported up to Elasticsearch 2.x libraries
- ES 2.x libraries do not specify Content-Type headers, because ES 2.x did not require it.
- ES 6.x now requires Content-Type header to be explicitly set
- You are using ES 2.x libraries to communicate with an ES 6.x server

Solution: 
Latest commit bumped Elasticsearch libraries to ~6.0, so this issue should be resolved.

**Comment by AnalistJeFF** [comment]
Any solution guys ???

**Comment by apoorvtomar2222** [comment]
I am using elastic search client to make the search query request. In that case, I just set my header and it worked.

Eg:

```
elasticClient.search({
      type: 'data',
     header:{
                 //set ur content type here
     }
      body: {
        query: {
          bool: {
            must: [
              { match: { 'title': searchParam } },
              { match: { 'published': 1 } },
            ]
          }
        },
        from: lowerLimit, size: higherLimit,
      }
    }
```

**Comment by basvandorst** [comment]
The problem is that the current version of this library (1.0.6) has the following dependency:
` "elasticsearch/elasticsearch": ">1.0 <2.1"`

The last version of this library (dev-master) has the following dependency:
` "elasticsearch/elasticsearch": "~6.0"`

You could fix this issue by pointing elasticquent to dev-master:
`"elasticquent/elasticquent": "dev-master"`

Of course, a better solution is that the owner of this repo will create a new tag
