### ISSUE TITLE
_id gets set to 0 in some cases

### ISSUE THREAD

**Issue by eissmann** [elasticquent/Elasticquent#210]
https://github.com/elasticquent/Elasticquent/blob/0281bb0b85c57ed287dbe8ced3dbd5917b006a04/src/ElasticquentTrait.php#L593

I just had an issue with a mongoDB-ID. "5e2736479201327028213292" is the generated id.

is_numeric("5e2736479201327028213292") is true and intval("5e2736479201327028213292") is 0

The result is, that the id in my results are set to 0.

**Comment by coffeeburrito** [comment]
This fix is highly problematic for UUIDs. For example, intval("18bd34a7223c6e2fb831a15e0384b153") returns "18"

I suspect a simple replacement of "is_numeric" with "is_int" would have worked better, since is_numeric('5e2736479201327028213292') is true but is_int('5e2736479201327028213292') is false.

I can't imagine anyone is using non-int numeric IDs (float?), but maybe someone else can think of a more ideal solution?
