### ISSUE TITLE
How to put index settings such as analyzer when creating index or add meta-fields when put mapping?

### ISSUE THREAD

**Issue by xian13** [elasticquent/Elasticquent#22]
Hi @timgws,

I have a difficulty when i want to put custom analyzer when creating index, or adding meta-fields like _all when put mapping.

Can I make modification to the createIndex and putMapping, before the default parameters is sent to the create / putMapping, we can sent it to getCreateIndexParameters and getMappingParameters, so we can easily override that if we want to.

```
    public static function createIndex($shards = null, $replicas = null)
    {
        $instance = new static;

        $client = $instance->getElasticSearchClient();

        $index = array(
            'index' => $instance->getIndexName(),
        );

        if (!is_null($shards)) {
            $index['body']['settings']['number_of_shards'] = $shards;
        }

        if (!is_null($replicas)) {
            $index['body']['settings']['number_of_replicas'] = $replicas;
        }

        return $client->indices()->create($this->getCreateIndexParameters($index));
    }

    public function getCreateIndexParameters(array $defaultParameters)
    {
        return $defaultParameters;
    }
```

```
    public static function putMapping($ignoreConflicts = false)
    {
        $instance = new static;

        $mapping = $instance->getBasicEsParams();

        $params = array(
            '_source' => array('enabled' => true),
            'properties' => $instance->getMappingProperties(),
        );

        $mapping['body'][$instance->getTypeName()] = $params;

        return $instance->getElasticSearchClient()->indices()->putMapping($this->getMappingParameters($mapping));
    }

    public function getMappingParameters(array $defaultParameters)
    {
        return $defaultParameters;
    }
```

And also I want to add some function for checking and index exists or not (just like typeExists) and recreateIndex (check index exists or not, if exists and forced, delete the index and create it, if not exists just create it).

If you agree, i will create PR for this.

Thank you.

**Comment by petercoles** [comment]
@xian13

I completely agree with your ideas of areas into which Elasticquent could useful expand, but have some concerns about the proposed approach.

The way in which Elasticquent extends Eloquent models to facilitate indexing and search against the data that they represent is fantastic. But giving those models the ability to create, delete and otherwise manipulate whole indices seems to me to give them too much power.

Suppose, for example, you were building an e-commerce site and wished to index products, customers and orders for rapid searching. It seems to me wrong (and rather dangerous) that the product model would have the ability to delete a whole index including customer and order data. That's way more power than Laravel entrusts to its models.

So my preference would be to move index maintenance out of the trait (so that it's no longer available to models) and into a service class that application developers could inject into an admin index controller, an artisan command or a Laravel migration as needed. A similar approach could be used for type maintenance.

However, although this would provide a more robust platform for expanding the Elasticsearch functionality to which Elasticquent provide access, while also controlling, even reducing, the complexity of the package, it would also involve breaking changes for users already using the rudimentary index maintenance already in Elasticquent. So I guess the best approach comes down to whatever plans @timgws has for the future development of this package.
