### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by HazeDevelopment** [elasticquent/Elasticquent#24]
Since laravel 5.2 the dev-master commits are broken.

I get the following error: 

```
Fatal error: Class 'ElasticquentResultCollection' not found in /vendor/elasticquent/elasticquent/src/ElasticquentTrait.php on line 253
```

**Comment by petercoles** [comment]
I've not seen that with normal 5.2 usage, but I have seen it when trying to write tests. I think it's to with the static methods trying to instantiate a new instance of a class that's in a different namespace to the trait. I'm about to put up a pull request that fixes this for the examples that I've seen, and since I'm using that code with Laravel 5.2 app too, if accepted, it will hopefully deal with your issue too.

**Comment by timgws** [comment]
There was an issue with the `use` statements. I am releasing `v1.0.5` right now to fix this issue.

```php
Route::get('test', function () {
    Book::createIndex();
    Book::addAllToIndex();

    $books = Book::search('Life');
    print_r($books->getHits());
});
```
